CREATE TABLE `xdfvisitoruser` (
  `userId` char(36) NOT NULL,
  `tenantId` int(11) DEFAULT '0',
  `nicename` varchar(280) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `trueName` varchar(45) DEFAULT NULL,
  `sex` int(11) DEFAULT '0',
  `qq` varchar(45) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,  
  `telephone` varchar(45) DEFAULT NULL,
  `mobilephone1` varchar(45) DEFAULT NULL,
  `mobilephone2` varchar(45) DEFAULT NULL,
  `studentNo` varchar(45) DEFAULT NULL,
  `studentType` varchar(45) DEFAULT NULL,
  `studentGrade` varchar(45) DEFAULT NULL,
  `studentSchool` varchar(45) DEFAULT NULL,
  `consultCategory` varchar(45) DEFAULT NULL,
  `consultDept` varchar(45) DEFAULT NULL,
  `recommendIllustrate` varchar(45) DEFAULT NULL,
  `className1` varchar(45) DEFAULT NULL,
  `classNo1` varchar(45) DEFAULT NULL,
  `className2` varchar(45) DEFAULT NULL,
  `classNo2` varchar(45) DEFAULT NULL,
  `purposeClass` varchar(45) DEFAULT NULL,
  `creator` varchar(45) DEFAULT NULL,
  `companyName` varchar(45) DEFAULT NULL,
  `description` varchar(200) DEFAULT NULL,
  `followAgent` varchar(45) DEFAULT NULL,
  `consultOrderType` varchar(45) DEFAULT NULL,
  `createDateTime` datetime DEFAULT NULL,
  `lastUpdateDateTime` datetime DEFAULT NULL,
  PRIMARY KEY (`userId`),
  KEY `IDX_TENANT` (`tenantId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
