services:
  - redis
  - docker
language: java
sudo: false
install: true
jdk: oraclejdk8
script: 
  - ./travis.sh
before_install:
  - curl -OfsSL https://raw.github.com/easemob/kefu-scripts/master/travis.sh
  - chmod +x travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 5c147469-e9d3-4fea-9963-474d5612cfaf
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    
notifications:
  slack: easemob:tYWZJo2ydkdNkexGpLSVFac5    
